version: '3.9'
services:
  frontend:
     build: ./frontend
     container_name: angular-container
     ports:
       - "4200:4200"
     volumes:
       - "./frontend:/app"
     tty: true
  backend:
      image: node:18-slim
      container_name: express-container
      environment:
       - DEBUG=backend:*
#ホットリロード（ソースの変更を即時反映）をON
       - CHOKIDAR_USEPOLLING=truecd
      tty: true
      ports:
       - '3000:3000'
       #ホスト側のbackendをコンテナのappにマウント
      volumes:
       - ./backend:/app
      #起動時のカレントフォルダ
      working_dir: /app

      command: 
        sh -c 'npx tsc; npm run nodemon'
  DB:
     image: 'postgres:15' 
     container_name: postgres-container
     restart: always
     environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD=: postgres_pw
      POSTGRES_DATABASE: postgres
     ports: 
     - '5432:5432' 
     volumes: 
     - 'postgres:/var/lib/postgresql/data'
volumes:
 postgres: