version: '3.9'
services:
  frontend:
     build: ./frontend
     container_name: angular-container
     ports:
       - "4200:4200"
     volumes:
       - "./frontend:/app"
     tty: true
  backend:
      image: node:18-slim
      container_name: express-container
      environment:
       - DEBUG=backend:*
       - CHOKIDAR_USEPOLLING=truecd
      tty: true
      ports:
       - '3001:3001'
       - '5555:5555'
      volumes:
       - ./backend:/app
      working_dir: /app
      depends_on:
      - DB

      
  DB:
     image: 'postgres:15' 
     container_name: postgres-container
     restart: always
     environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
     ports: 
     - '5432:5432' 
     volumes: 
     - 'postgres:/var/lib/postgresql/data'
volumes:
 postgres: